name: talent-within
dependencies:
  - python >=3.9,<3.11
  - boto3
  - fastapi
  - numpy
  - openpyxl
  - pandas
  - pip
  - python-dotenv
  - scipy
  - uvicorn
  - yaml
  - pip:
    - PyMuPDF
    - PyYAML
    - streamlit
    - streamlit-extras
    - streamlit-option-menu
    # - transformers
    # - torch